//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForms_Samples.Samples {
    
    
    public partial class ToggleUseAltNames {
        
        /// <summary>
        /// QueryBuilderControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ActiveQueryBuilder.Web.WebForms.QueryBuilderControl QueryBuilderControl1;
        
        /// <summary>
        /// ObjectTreeView1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ActiveQueryBuilder.Web.WebForms.ObjectTreeView ObjectTreeView1;
        
        /// <summary>
        /// SubQueryNavigationBar1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ActiveQueryBuilder.Web.WebForms.SubQueryNavigationBar SubQueryNavigationBar1;
        
        /// <summary>
        /// Canvas1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ActiveQueryBuilder.Web.WebForms.Canvas Canvas1;
        
        /// <summary>
        /// StatusBar1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ActiveQueryBuilder.Web.WebForms.StatusBar StatusBar1;
        
        /// <summary>
        /// Grid1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ActiveQueryBuilder.Web.WebForms.Grid Grid1;
        
        /// <summary>
        /// SqlEditor1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ActiveQueryBuilder.Web.WebForms.SqlEditor SqlEditor1;
    }
}
